In [1]:
import numpy as np
import math

In [2]:
input = np.random.randint(10, size=(5,5))
kernel = np.random.randint(0,2,(3,3))

In [3]:
def convolve(input, kernel, padding, stride):
  Nout = int((((input.shape)[0] + (2*padding) - (kernel.shape)[0])/stride) + 1)
  output = np.zeros((Nout, Nout))
  x=0
  y=0
  size = len(output[0])
  for j in range(0,size):
    for i in range(0,size):
      submatrix = input[x:x+(kernel.shape)[0],y:y+(kernel.shape)[0]]
      output[j][i] = (np.multiply(submatrix,kernel)).sum()
      y = y + stride
    y = 0
    x = x + stride
  return output   

In [4]:
padding = 0
stride = 1

**STRIDE 1**

In [5]:
output1 = convolve(input, kernel, padding = 0 ,stride = 1)

In [6]:
output1

array([[37., 35., 43.],
       [44., 34., 41.],
       [33., 33., 24.]])

**STRIDE 2**

In [7]:
output2 = convolve(input, kernel, padding = 0 ,stride = 2)

In [8]:
output2

array([[37., 43.],
       [33., 24.]])

In [9]:
def Pooling(input,filterShape,stride,poolingType):
  Nout = int((((input.shape)[0] - filterShape)/stride) + 1)
  output = np.zeros((Nout, Nout))
  x = y = 0
  size = len(output[0])
  for j in range(0,size):
    for i in range(0,size):
      submatrix = input[x:x + filterShape,y:y + filterShape]
      if poolingType == 'max':
        output[j][i] = submatrix.max()
      elif poolingType == 'average':
        output[j][i] = np.average(submatrix)
      else:
        output[j][i] = submatrix.sum()
      y = y + stride
    y = 0
    x = x + stride 
  return output    

**Sum Pooling**

In [10]:
sumPooled = Pooling(output1,2,1,'sum')
print("Sum Pooling : \n",sumPooled)

Sum Pooling : 
 [[150. 153.]
 [144. 132.]]


**Average Pooling**

In [11]:
avgPooled = Pooling(output1,2,1,'average')
print("Average Pooling : \n",avgPooled)

Average Pooling : 
 [[37.5  38.25]
 [36.   33.  ]]


**Max Pooling**

In [12]:
maxPooled = Pooling(output1,2,1,'average')
print("Maximum Pooling : \n",maxPooled)

Maximum Pooling : 
 [[37.5  38.25]
 [36.   33.  ]]


In [13]:
sumPooledFlattened = sumPooled.flatten()
print("Flattened version of sum pooled: ",sumPooled.flatten())

Flattened version of sum pooled:  [150. 153. 144. 132.]


In [14]:
avgPooledFlattened = avgPooled.flatten()
print("Flattened version of average pooled: ",avgPooledFlattened)

Flattened version of average pooled:  [37.5  38.25 36.   33.  ]


In [15]:
maxPooledFlattened = maxPooled.flatten()
print("Flattened version of max pooled: ", maxPooledFlattened)

Flattened version of max pooled:  [37.5  38.25 36.   33.  ]


In [16]:
X = []
(X.append(maxPooledFlattened[0:]))
T = np.array([[1]])
W1 = np.random.uniform(size=(1,4),low = -0.5, high = 0.8)
W2 = (np.random.uniform(size=(1,2),low = -0.5, high = 0.8))[0]
B1 = np.array([1,1])
B2 = np.array([0.5])
alpha = 0.1
epoch = 200
error_tolerance = 0.40

In [17]:
def BipolarSigmoid(x):
  return (2/(1+math.exp(-x))) - 1

In [18]:
def BipolarSigmoidDerivative(x):
  return 0.5*(1-x)*(1+x) 

In [19]:
def DeltaHidden(delta_in, Z):
  return delta_in * BipolarSigmoidDerivative(Z)

In [28]:
def Perceptron(x,w1,w2,b1,b2,t,a,e):
  for count in range(e):
    for i,row in enumerate(x):
      Zin = np.dot(row,w1.T) + b1
      Zout = np.vectorize(BipolarSigmoid)(Zin)
      Yin = np.dot(Zout,w2.transpose()) + b2
      Y = np.vectorize(BipolarSigmoid)(Yin)
      if(t[1] != Y[0]):
        delta_y = (t[i] - Y) * (BipolarSigmoidDerivative(Y))
        delta_in_z = delta_y * w2
        delta_Z = delta_in_z * np.vectorize(BipolarSigmoidDerivative)(Zout)
        for index in range(len(w1)):
          w1[index] = (w1[index].T + a*delta_Z[index]*row.T).T
        w2 = (w2.T + a*delta_y*Zout.T).T
        b1 = b1 + a*delta_Z
        b2 = b2 + a*delta_y
  return GetResult(w1,w2,b1,b2)   

In [29]:
def GetResult(w1,w2,b1,b2):
  result=[]
  result.append(w1)
  result.append(w2)
  result.append(b1)
  result.append(b2)
  return result

In [ ]:
epoch =1
adjustedweights=Perceptron(X,W1,W2,B1,B2,T,alpha,epoch)
W1=adjustedweights[0]
W2=adjustedweights[1]
B1=adjustedweights[2]
B2=adjustedweights[3]

In [32]:
print("W1 : ",W1)
print("W2 : ",W2)
print("B1 : ",B1)
print("B2 : ",B2)

W1 :  [[-0.35982032  0.17316977 -0.34057831 -0.31769124]]
W2 :  [ 0.16697195 -0.24814035]
B1 :  [1 1]
B2 :  [0.5]
